FROM python:3.11 
WORKDIR /app
ENV VIRTUAL_ENV=/opt/venv
RUN python -m venv $VIRTUAL_ENV

ENV TG_TARGET=/tg_files
RUN mkdir ${TG_TARGET}
RUN mkdir /target


COPY API ./API
COPY db ./db
COPY API_run.py . 

RUN pip install pipreqs
RUN pipreqs . --savepath ./requirements.txt
RUN pip install -r requirements.txt
#RUN pip uninstall ffmpeg
RUN pip install ffmpeg-python 
RUN pip install pymysql
RUN pip install cryptography 
RUN apt update
RUN apt -y install ffmpeg


#ENV PORT=5000
#EXPOSE ${PORT}
CMD ["sh", "-c", "python API_run.py"]
