services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile_bot
    environment:
      BOT_API_URL: "http://tg_api:8081"
      API_URL: "http://api:5000"
      BOT_TOKEN: "<bot_token>"
      REDIS_CREDITS: "<redis_url>:<redis_port>:<redis_password>"
  tg_api:
    build:
      context: .
      dockerfile: Dockerfile_tg_bot_api
    volumes:
      - ./tg_files:/tg_files
#    ports:
#      - "8081:8081"
    expose:
      - "8081"
    environment:
      TELEGRAM_API_ID: "api_id"
      TELEGRAM_API_HASH: "api_hash"
      HTTP_PORT: "8081"
      TARGET_DIR: "/tg_files"
  api:
    build:
      context: .
      dockerfile: Dockerfile_api
    volumes:
      - ./tg_files:/tg_files
      - ./target:/target
#    ports:
#     - "5000:5000"
    expose:
      - "5000"
    environment:
      PORT: "5000"
      TG_TARGET: "/tg_files"


